### PR TITLE
Controlled data return

### PR DESCRIPTION
**Pull request by blackary**
Adds an argument for specifying what data gets returned from the bidrectional st_folium via an argument `returned_objects`. Anything that is not returned does not cause an app return. If you pass an empty list, it returns an empty dictionary. This leads to a simple rewrite of folium_static to simply call st_folium with an empty list of data items to return.

Also refactored the example app into a MPA and added a page showing the new limited-return functionality.

e.g. `st_folium(m, returned_objects=["last_clicked"])` -- app would only return the last value clicked, and any other map interactions would not change the value returned, or trigger an app rerun.

Resolves: #85
Resolves: #77

### CODE REVIEW

**Comment by randyzwitch** [comment]
Conceptually, I'm fine with this. I know that you are bumping the minor version to indicate the breaking change, but it might not be worth ever changing `folium_static` at this point? 

Unless you're ripping the band-aid off and will be dedicated to figuring out why there are differences to make `st_folium` the canonical way to use the package.

**Comment by nathanjones4323** [comment]
Thank you for the continued work on this component, I really appreciate it.

It has made working with Folium so much more useful !

**Comment by randyzwitch** [comment]
Chickening out seems right for now :) I can bump this to 0.6.16, so it's available for use.

**Comment by TomAspinall** [comment]
Amazing!! Thank you so much - this update works fantastically!

**Pull request merged**
