### PR TITLE
Created complex example

### PR DESCRIPTION
**Pull request by juancalvof**
Created complex example with st.selectbox() and 3 folium maps to select.

### CODE REVIEW

**Comment by randyzwitch** [comment]
Thanks for taking a shot at this @juancalvof. What I was hoping for was less about lots of different maps, but a real data example. Something beyond a single data point that is what already exists, but not random data either.

**Comment by juancalvof** [comment]
OK. I understand. I'm working in the next weeks on a personal project that may fit.

I have done another Pull Request trying to add my last commit, "Add full screen functionality" to the "streamlit_folium_example.py", but I have send again the 3 previous commits by accident.

**Comment by randyzwitch** [comment]
For a pull request, it doesn't really matter whether you use cherry-pick or not. Any matching commits don't get added (I only see a single new commit here), and once the PR is approved, I was squash all the changes into a single commit.

**Comment by juancalvof** [comment]
> Thanks Juan for the full screen plugin. That worked great. But is there a way to change the standard folium map size before clicking the full screen button?

For changing the map size in Streamlit you can use the argument of the function folium_static(), height, weight, that goes to components.html().

**Pull request closed without merging**
