### PR TITLE
Improve performance on maps with many children

### LINKED ISSUE #125: Performance issue when working with many points
The time it takes for `st_folium` to return with `returned_objects` seems to be proportional to the number of objects displayed on the map. I am plotting many markers and lines, but in the end I am only interested in the point that the user has clicked, i.e.

```
st_data = st_folium(m, returned_objects=["last_object_clicked"])
```
The trouble is, with many points it can take e.g. 10 seconds to return. If I make the map static, it's nearly instant.

Is there anything I can do to improve the performance, short of reducing the number of points?

### PR DESCRIPTION
**Pull request by hugosandelius**
This change will significantly improve the running time of `st_folium` on maps with many children.
In an example I tried with 10,336 child objects, the running time was improved from ~14 seconds to ~400 milliseconds.

Fixes #125

### CODE REVIEW

**Comment by randyzwitch** [comment]
Looks like this is failing due to the pre-commit hook for Black formatting

**Comment by hugosandelius** [comment]
I force-pushed a fix for the formatting, the pre-commit hook should pass now.

**Comment by nathanjones4323** [comment]
Super excited to try this out!

**Comment by randyzwitch** [comment]
@blackary Can you try to run these tests locally, or change the timeout of 30000ms? That's what keeps failing, the actual tests never even run

**Comment by blackary** [comment]
I think some of the failures were literally because the playwright window was too small to see the map 🤦

**Review by blackary — APPROVED** [review]
🚀

**Pull request merged**
