### PR TITLE
bump node to current LTS & adapt build accordingly

### PR DESCRIPTION
**Pull request by BastienGauthier**
This fix https://github.com/randyzwitch/streamlit-folium/issues/127

The main blocker was streamlit-component-lib not upgrading to v2

### CODE REVIEW

**Comment by blackary** [comment]
I think it's probably best to actually pin the package requirements as well until we figure out a solution to the folium 0.15 bug

**Comment by BastienGauthier** [comment]
> I think it's probably best to actually pin the package requirements as well until we figure out a solution to the folium 0.15 bug
Not sure hat you mean here : I set folium>=0.13,<0.15 for both requirement.txt files already. You mean you want folium==0.14 exactly ?

**Comment by blackary** [comment]
Sorry, it's a bit confusing -- there are 3 different sets of requirements in this repo:
1. requirements.txt -- for the demo app
2. test/requirements.txt -- for the tests
3. setup.py -- for the package

You should actually just be able to change the requirements in the package, and have it work, since the requirements.txt files should also install the package dependencies

**Comment by BastienGauthier** [comment]
done !

**Review by blackary — APPROVED** [review]
Thanks!

**Pull request merged**
