### PR TITLE
Remove extra requirements and change year

### PR DESCRIPTION
**Pull request by randyzwitch**
Extra requirements.txt file was from when Streamlit Cloud didn't support subfolders for requirements. Updated license to current year.

### CODE REVIEW

**Comment by sfc-gh-zblackwood** [comment]
Even though the requirements.txt isn't required, I actually like leaving it there, to make it easier for people who want to clone this repo and work with it locally. It allows us to have more detailed development dependencies, for example, that aren't strictly required for pip installing this package. But, not a big deal, as the dependencies are pretty minimal.

**Comment by blackary** [comment]
Even though the requirements.txt isn't required, I actually like leaving it there, to make it easier for people who want to clone this repo and work with it locally. It allows us to have more detailed development dependencies, for example, that aren't strictly required for pip installing this package. But, not a big deal, as the dependencies are pretty minimal.

**Review by blackary — APPROVED** [review]
My vote would be to leave the requirements file for developers working with this repo, but no big deal either way.

**Comment by randyzwitch** [comment]
>It allows us to have more detailed development dependencies, for example, that aren't strictly required for pip installing this package.

Good point

**Pull request closed without merging**
