### PR TITLE
Add VectorGrid support

### LINKED ISSUE #107: folium-vectorgrid support?
Hi,  currently using 0.8.1 of streamlit-folium to render a map and I was hoping to use `folium.plugins.VectroGridProtobuf` as a layer to serve vector tiles.  If i save out my folium to an index.html i'm getting a good map with vector tiles displaying,  but using streamlit-folium  i'm seeing 

```
Uncaught TypeError: L.vectorGrid is undefined
    <anonymous> index.html:22
    onRender index.tsx:192
    dispatchEvent event-target.mjs:337
    onRenderMessage streamlit.js:172
    onMessageEvent streamlit.js:143
index.html:22:38
    <anonymous> index.html:22
    onRender index.tsx:192
    dispatchEvent event-target.mjs:337
    onRenderMessage streamlit.js:172
    onMessageEvent streamlit.js:143
```

Do I need to do something extra to build vectrogrid support into the JS that is bundled? Sorry my familiarity with the javascript ecosystem is somewhat limited.  Thanks for all your hard work!

### PR DESCRIPTION
**Pull request by blackary**
Fixes #107

### CODE REVIEW

**Comment by kotfic** [comment]
Tested locally,  getting good vector tiles. Thanks!

**Comment by kotfic** [comment]
FWIW setting `"interactive": True` on the VectorGridProtobuf layer causes errors due to an upstream bug https://github.com/Leaflet/Leaflet.VectorGrid/issues/273 Not sure there is anything to do about it.

**Comment by randyzwitch** [comment]
This has a merge conflict now @blackary

**Comment by blackary** [comment]
@kotfic If the bug is on the underlying Leaflet library, it will likely be difficult to fix in this package (not necessarily impossible, but much more difficult, since this is two layers above leaflet -- leaflet -> folium -> streamlit-folium). Do you have an example streamlit script which shows the issue?

**Review by randyzwitch — APPROVED** [review]

**Comment by kotfic** [comment]
@blackary yeah sorry not suggesting any action item on this PR.  There are 4 or 5 issues on Leaflet.VectorGrid describing the problem,  seeing as the last real commit on that library was July 2019 I don't have much hope of it being fixed.  Its just a bummer that it has the function (so the duck typing passes)  but the function is broken. It is equally a bummer that leaflet/javascript doesn't support determining the layer type so `onLayerClick` can't easily skip implement a code path that avoids the exception.

**Pull request merged**
