### PR TITLE
[WIP] Bidirectional

### PR DESCRIPTION
**Pull request by randyzwitch**
Experiment to see what it would take to have bi-directional communication

### CODE REVIEW

**Comment by randyzwitch** [comment]
Per internal discussion, this is probably blocked by a feature-in-progress, will come back in a few weeks once that feature is ready

**Comment by randyzwitch** [comment]
When https://github.com/streamlit/streamlit/pull/2466 merges, work can resume on this issue

**Comment by aadilh** [comment]
Hey @randyzwitch, was there any update on this? I am specifically looking for capturing which folium marker was clicked so that I can update the content outside map based on the selected marker. I am not sure whether it will be possible with this bi-directional support.

**Comment by randyzwitch** [comment]
No, no update. This isn't something I know how to do, unfortunately, haven't had the time to get someone else to take a look at it.

**Comment by randyzwitch** [comment]
Closing this for now since I'm not actively working on it, will revisit at a later date.

**Pull request closed without merging**
