### PR TITLE
docs: include link to PyCafe for a live example

### PR DESCRIPTION
**Pull request by maartenbreddels**
Hi Randy,

I think it would be nice if people can play directly with your library on https://py.cafe
I don't know if you like that the link to the project links to a personal project of mine.
If something needs to change, you can always fork it, edit it and point to your project.

Let me know what you think.

Regards,

Maarten

Including the markdown below so you can preview it:
---

[PyCafe logo Run and edit this example in Py.Cafe](https://py.cafe/maartenbreddels/streamlit-folium-geospatial-visualizations)

### CODE REVIEW

**Comment by randyzwitch** [comment]
Hey @maartenbreddels, thanks for the PR! Don't mind that it's in your account, though, is there any benefit to having my own account (for maintenance or anything else)?

**Comment by maartenbreddels** [comment]
Yeah, purely so you can edit it yourself. Now, if you want to make a change you can

1. ask me
2. fork it, edit and push

**Comment by maartenbreddels** [comment]
No idea why I cannot re-open this PR, do you have permissions/rights to do that?

**Comment by randyzwitch** [comment]
I'll merge this, and if it's popular enough where someone asks for an update, then we can pursue making an account for me

**Comment by maartenbreddels** [comment]
Thanks Randy. You can log in with your GitHub account if you need to fork and edit.

**Pull request merged**
